### ISSUE TITLE
您好，我想请教一下，我是按照描述安装的pytorch1.4，但是进行训练时错误如下？似乎是版本太过陈旧，然后我更换到1.12以上又会报其他错误。请问大佬这是什么原因？

### ISSUE THREAD

**Issue by fonsjiang** [layumi/person-reid-3d#20]
(OG) francisjiang@francisjiang:~/desktop/person-reid-3d$ python train_M.py --batch-size 30 --name Market_Efficient_ALL_2SDDense_b30_lr6_flip_slim0.5_warm10_scale_e0_d7+bg_adam_init768_clusterXYZRGB_e1000_id2_bn_k9_conv2_balance  --id_skip 2 --slim 0.5 --flip --scale  --lrRate 6e-4 --gpu_ids 0 --warm_epoch 10  --erase 0  --droprate 0.7   --use_dense  --bg 1  --adam  --init 768  --cluster xyzrgb  --train_all   --num-epoch 1000  --feature_dims 48,96,96,192,192,384,384  --efficient --k 9  --num_conv 2  --dataset 2DMarket --balance --gem --norm_layer bn2 --circle --amsgrad --gamma 64
/home/francisjiang/anaconda3/envs/OG/lib/python3.7/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cpu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "train_M.py", line 6, in <module>
    from market3d import Market3D
  File "/home/francisjiang/desktop/person-reid-3d/market3d.py", line 1, in <module>
    from torchvision import datasets
  File "/home/francisjiang/anaconda3/envs/OG/lib/python3.7/site-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/home/francisjiang/anaconda3/envs/OG/lib/python3.7/site-packages/torchvision/models/__init__.py", line 2, in <module>
    from .convnext import *
  File "/home/francisjiang/anaconda3/envs/OG/lib/python3.7/site-packages/torchvision/models/convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "/home/francisjiang/anaconda3/envs/OG/lib/python3.7/site-packages/torchvision/ops/__init__.py", line 2, in <module>
    from .boxes import (
  File "/home/francisjiang/anaconda3/envs/OG/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 78, in <module>
    @torch.jit._script_if_tracing
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'

**Comment by layumi** [comment]
Hi @fonsjiang 

Please see https://github.com/pytorch/pytorch/issues/42078 
```
pip uninstall torchvision
pip install torchvision==0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
```

Please check the torchvision version. It should match the pytorch version as follows.
<img width="641" alt="image" src="https://github.com/layumi/person-reid-3d/assets/8390471/f4465cc7-0ec8-499e-b02b-b8a65c45470a">
